DELETE FROM public.user_dictionary;
COMMIT;
INSERT INTO public.user_dictionary (id,user_name, first_name) VALUES  (1, 'pushkin', 'Serega');
COMMIT;
INSERT INTO public.user_dictionary (id,user_name, first_name) VALUES  ('2', 'raptil', 'Alex');
COMMIT;
DELETE FROM public.chat_message;
COMMIT;
INSERT INTO public.chat_message (id, name) VALUES  ('1', 'Big benefits');
COMMIT;
DELETE FROM public.chat_to_user;
COMMIT;
INSERT INTO public.chat_to_user(id_user, id_chat) VALUES  ('1', '1');
COMMIT;
INSERT INTO public.chat_to_user (id_user, id_chat) VALUES  ('2', '1');
COMMIT;
DELETE FROM public.message;
COMMIT;
INSERT INTO public.message (id, id_chat, id_user, message) VALUES  ('1', '1', '1', 'Hello, guys!');
COMMIT;
INSERT INTO public.message (id, id_chat, id_user, message) VALUES  ('2', '1', '2', 'Hello, guys!');
COMMIT;
